on: [workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n kingoliver2 -g kingoliver297b4-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n kingoliver2 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n kingoliver2 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n kingoliver2 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: kingoliver2.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t kingoliver2.azurecr.io/kingoliver2:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push kingoliver2.azurecr.io/kingoliver2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kingoliver2_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kingoliver2990e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kingoliver2990e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kingoliver2990e
        container-registry-url: kingoliver2.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kingoliver2dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kingoliver2990e
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          kingoliver2.azurecr.io/kingoliver2:${{ github.sha }}
        imagepullsecrets: |
          kingoliver2dockerauth   
